-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQggJW+cxF5luUCtesJ
lxWJcVD6+rNrrjxiikvDksTnXpmgCgYIKoZIzj0DAQehRANCAARisC0ZRuJfmAMf
BflcvuTqA/xXV7wBPRwCLZyeOCDzRzjhPbWHXGeYujAeY2WsL07H1VsJcn9I3ext
Z/lL0dBJ
-----END PRIVATE KEY-----