export const TRANSACTION = {
  INITIAL_NOTE: 'Welcome to Jibber',
  TARGET: 'wallet',
  CATEGORY: 'transaction',
  EVENT_TYPE: {
    INTEREST_PAYMENT: "INTEREST_PAYMENT",
    INVITE_SENT: "INVITE_SENT",
    FIRST_MESSAGE: "FIRST_MESSAGE",
    FIRST_FEELING: "FIRST_FEELING",
    FIRST_UNREAD_MESSAGE: "FIRST_UNREAD_MESSAGE",
    FIRST_GROUP: "FIRST_GROUP",
    GROUP_OF_PLUS: "GROUP_OF_PLUS",
    BUG_BOUNTY: "BUG_BOUNTY",
    FEATURE_REQUEST: "FEATURE_REQUEST",
    FIRST_10K: "FIRST_10K",
    INVESTOR: "INVESTOR",
  }
};

export default TRANSACTION;